from rest_framework import viewsets, permissions
from django.db.models import Q
from permissions.custom_permissions import HasDynamicPermission
from .models import ActivityLog
from .serializers import ActivityLogSerializer

class ActivityLogViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = ActivityLogSerializer
    permission_classes = [HasDynamicPermission]
    required_permission = 'manage_users'

    def get_queryset(self):
        """
        Returns activity logs for Admin and regular User actions.
        Strictly excludes logs generated by Super Administrators.
        """
        return ActivityLog.objects.exclude(
            Q(user__is_superuser=True) |
            Q(user__role__name__iexact='Super Admin') |
            Q(user__role__name__icontains='Super Admin')
        ).order_by('-created_at')
