# Generated by Django 5.2.16 on 2026-08-05 18:32

import customization.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Configuration', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('info', models.JSONField(default=customization.models.default_info)),
                ('branding', models.JSONField(default=customization.models.default_branding)),
                ('theme', models.JSONField(default=customization.models.default_theme)),
                ('navigation', models.JSONField(default=customization.models.default_navigation)),
                ('pages', models.JSONField(default=dict)),
                ('login', models.JSONField(default=customization.models.default_login)),
                ('dashboard', models.JSONField(default=customization.models.default_dashboard)),
                ('footer', models.JSONField(default=customization.models.default_footer)),
                ('notification', models.JSONField(default=customization.models.default_notification)),
                ('email_templates', models.JSONField(default=customization.models.default_email_templates)),
                ('error_pages', models.JSONField(default=customization.models.default_error_pages)),
                ('dynamic_text', models.JSONField(default=customization.models.default_dynamic_text)),
                ('custom_code', models.JSONField(default=customization.models.default_custom_code)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customization_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Customization',
                'verbose_name_plural': 'Website Customizations',
            },
        ),
    ]
