# Generated by Django 5.2.17 on 2026-08-18 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mous', '0008_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'stream', 'category')},
        ),
    ]
