# Generated by Django 5.2.17 on 2026-08-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mous', '0009_alter_department_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moucategory',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='moucategory',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mou_categories', to='mous.stream'),
        ),
        migrations.AlterField(
            model_name='moucategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='moucategory',
            unique_together={('name', 'stream')},
        ),
    ]
