# Generated by Django 5.2.16 on 2026-08-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0008_remove_folder_beneficiaries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Signed', 'Signed'), ('Pending Review', 'Pending Review'), ('Expired', 'Expired'), ('Archived', 'Archived')], db_index=True, default='Active', max_length=50),
        ),
    ]
