# Generated by Django 5.2.16 on 2026-08-07 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0010_folder_deleted_at_folder_deleted_by_and_more'),
        ('users', '0023_alter_customuser_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='custom_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_folders', to='users.customdynamicpage'),
        ),
        migrations.AddField(
            model_name='folder',
            name='module_type',
            field=models.CharField(db_index=True, default='mou_repository', max_length=100),
        ),
    ]
