# Generated by Django 5.2.17 on 2026-08-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0011_folder_custom_page_folder_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='import_source',
            field=models.CharField(blank=True, default='local', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='source_google_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
