# Generated by Django 5.2.17 on 2026-09-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0012_folder_import_source_folder_source_google_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='signed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
