# Generated by Django 5.2.16 on 2026-08-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0003_activitylog_user_agent_activitylog_user_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user_company',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user_department',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user_role',
        ),
    ]
