# Generated by Django 5.2.16 on 2026-08-06 02:40

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_password_changed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDynamicPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('icon', models.CharField(default='Folder', max_length=100)),
                ('route', models.CharField(default='/custom-page', max_length=255)),
                ('parent_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('badge_color', models.CharField(default='#3B82F6', max_length=50)),
                ('page_type', models.CharField(default='Folder Repository', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(default=list)),
                ('allowed_permissions', models.JSONField(default=list)),
                ('theme_colors', models.JSONField(default=dict)),
                ('crud_permissions', models.JSONField(default=dict)),
                ('entity_schema', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
