# Generated by Django 5.2.16 on 2026-08-06 03:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_customdynamicpage_root_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdynamicpage',
            name='google_drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
