# Generated by Django 5.2.16 on 2026-08-06 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_googledrivesetting_website_root_folder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googledrivesetting',
            name='website_root_folder_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
