# Generated by Django 5.2.16 on 2026-08-07 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_googledrivesetting_website_root_folder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
