# Generated by Django 5.2.17 on 2026-08-14 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_customuser_password_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
