# Generated by Django 5.2.17 on 2026-08-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_file_deleted_at_file_deleted_by_file_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='import_source',
            field=models.CharField(blank=True, default='local', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='source_google_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
