# Generated by Django 5.2.17 on 2026-09-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_file_import_source_file_source_google_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='signed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
